In [ ]:
import re
import torch


x = torch.randn(3, requires_grad=True)
# requires_grad is set to True, so the gradient will be tracked
# when performing operations on the tensor.
# The tensor will be created with a random value of size 3.

print(x)

y = x + 2
print(y)

z = y * y * 3
z = z.mean()
print(z)

z.backward()
# dz/dx is computed and stored in x.grad.
# The backward() function computes the gradient of z with respect to x, also known as backpropagation.
# uses jacobian-vector product also known as the chain rule to compute the gradient of z with respect to x.

print(x.grad)
# The gradient of z with respect to x is stored in x.grad.

tensor([ 0.1643, -0.1414, -0.1182], requires_grad=True)
tensor([2.1643, 1.8586, 1.8818], grad_fn=<AddBackward0>)
tensor(11.6799, grad_fn=<MeanBackward0>)
tensor([4.3286, 3.7173, 3.7636])
