In [9]:
import re
import torch


x = torch.randn(3, requires_grad=True)
# requires_grad is set to True, so the gradient will be tracked
# when performing operations on the tensor.
# The tensor will be created with a random value of size 3.

print(x)

y = x + 2
print(y)

z = y * y * 3
z = z.mean()
print(z)

z.backward()
# dz/dx is computed and stored in x.grad.
# The backward() function computes the gradient of z with respect to x.

print(x.grad)
# The gradient of z with respect to x is stored in x.grad.

tensor([-1.3474,  0.3969,  1.2696], requires_grad=True)
tensor([0.6526, 2.3969, 3.2696], grad_fn=<AddBackward0>)
tensor(16.8614, grad_fn=<MeanBackward0>)
tensor([1.3052, 4.7937, 6.5393])
