In [1]:
import torch

In [2]:
x = torch.empty((2, 3))
# torch.empty creates an uninitialized tensor of the given size
# The values in the tensor are not set to zero or any other value
print(x)

tensor([[       nan, 1.1393e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
torch.rand(2, 3)
# torch.rand(2, 3) is a function that generates a tensor of shape (2, 3) with random values between 0 and 1

tensor([[0.4388, 0.6992, 0.3051],
        [0.4897, 0.0365, 0.1843]])

In [4]:
torch.zeros(2, 3)
# torch.zeros(2, 3) is a function that generates a tensor of shape (2, 3) filled with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2, 3)
# torch.ones() is a function that generates a tensor filled with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
x = torch.ones(2, 3, dtype=torch.int)
# torch.ones(2, 3, dtype=torch.int) is a function that generates a tensor of shape (2, 3) filled with ones and of type int
print(x.dtype)
# torch.int is an alias for torch.int32, which is a 32-bit integer type
# can be double/float, int, etc.
# torch.float is an alias for torch.float32, which is a 32-bit floating point type or even float16, etc.
# torch.double is an alias for torch.float64, which is a 64-bit floating point type
print(x.size())
# x.size() returns the size of the tensor, which is (2, 3) in this case

torch.int32
torch.Size([2, 3])


In [7]:
x = torch.tensor([[1, 2], [3, 4]])
# torch.tensor([[1, 2], [3, 4]]) creates a tensor from the given list of lists
print(x)

tensor([[1, 2],
        [3, 4]])


In [8]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x)
print(y)
z = x + y
z = torch.add(x, y)
# operations are add, sub, mul, div, etc.
# torch.add(x, y) adds the two tensors x and y element-wise
print(z)
# The above code creates two random tensors x and y of shape (2, 2) and adds them together to create a new tensor z

tensor([[-0.5648,  0.6244],
        [ 1.2316, -0.2947]])
tensor([[ 0.4548,  0.3233],
        [ 0.7920, -1.8765]])
tensor([[-0.1100,  0.9477],
        [ 2.0236, -2.1713]])


In [9]:
y.add_(x)
# The underscore at the end of the function name indicates that this operation modifies y in place

# in pytorch all functions that modify the tensor in place have an underscore at the end of the function name

tensor([[-0.1100,  0.9477],
        [ 2.0236, -2.1713]])

In [10]:
x = torch.randn(2, 3)
# torch.randn(2, 3, 4) creates a tensor of shape (2, 3, 4) with random values from a normal distribution with mean 0 and variance 1
# now tensor slicing
print(x[0])
# x[0] selects the first slice of the tensor x along the first dimension (0th dimension)
print(x[:, 0])
# x[:, 0] selects all rows and the first column of the tensor x
print(x[0, :])
# x[0, :] selects the first row and all columns of the tensor x
print(x[0, 0])
# x[0, 0] selects the first element of the first row of the tensor x
print(x[0, 0].item())
# x[0, 0].item() returns the value of the first element of the first row of the tensor x as a Python number
# The item() method is used to convert a single-element tensor to a Python number


tensor([ 0.4450,  0.1358, -1.4050])
tensor([0.4450, 0.1330])
tensor([ 0.4450,  0.1358, -1.4050])
tensor(0.4450)
0.44496411085128784


In [12]:
# Reshaping tensors
x = torch.randn(4, 4)
print(x)
print(x.size())
# x.size() returns the size of the tensor, which is (4, 4) in this case

y = x.view(16)
# x.view(16) reshapes the tensor x to a 1D tensor of size 16
print(y)
print(y.size())


y = x.view(-1, 8)
# x.view(-1, 8) reshapes the tensor x to a 2D tensor with 8 columns and as many rows as needed to accommodate all elements of x
# The -1 indicates that the number of rows should be inferred from the total number of elements in x
print(y)
print(y.size())
# The view() method is used to reshape a tensor without changing its data

tensor([[ 0.9008,  2.4073, -0.8396,  0.8952],
        [ 0.8994, -0.7621, -1.7258, -0.6819],
        [-0.3047,  0.6303, -2.2109, -0.0230],
        [ 0.2382,  1.4029, -1.0571, -1.2036]])
torch.Size([4, 4])
tensor([ 0.9008,  2.4073, -0.8396,  0.8952,  0.8994, -0.7621, -1.7258, -0.6819,
        -0.3047,  0.6303, -2.2109, -0.0230,  0.2382,  1.4029, -1.0571, -1.2036])
torch.Size([16])
tensor([[ 0.9008,  2.4073, -0.8396,  0.8952,  0.8994, -0.7621, -1.7258, -0.6819],
        [-0.3047,  0.6303, -2.2109, -0.0230,  0.2382,  1.4029, -1.0571, -1.2036]])
torch.Size([2, 8])


In [14]:
import numpy as np

In [16]:
a = torch.ones(5)
print(a)
b = a.numpy()
# a.numpy() converts the tensor a to a NumPy array
print(b)
print(type(b))
# The type of b is numpy.ndarray, which is a NumPy array

# if you modify the NumPy array, the original tensor is also modified if on cpu

a.add_(1)
# a.add_(1) adds 1 to each element of the tensor a in place
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
from numpy import dtype


a = np.ones(5)
# a = np.ones(5) creates a NumPy array of shape (5,) filled with ones
print(a)
b = torch.from_numpy(a, dtype=dtype("float32"))
# torch.from_numpy(a) converts the NumPy array a to a PyTorch tensor
print(b)
print(type(b))
# The type of b is torch.Tensor, which is a PyTorch tensor

[1. 1. 1. 1. 1.]


TypeError: torch._VariableFunctionsClass.from_numpy() takes no keyword arguments