In [3]:
import torch

In [ ]:
x = torch.empty((2, 3))
# torch.empty creates an uninitialized tensor of the given size
# The values in the tensor are not set to zero or any other value
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
torch.rand(2, 3)
# torch.rand(2, 3) is a function that generates a tensor of shape (2, 3) with random values between 0 and 1

tensor([[0.9873, 0.2139, 0.1368],
        [0.7794, 0.1619, 0.2240]])

In [10]:
torch.zeros(2, 3)
# torch.zeros(2, 3) is a function that generates a tensor of shape (2, 3) filled with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(2, 3)
# torch.ones() is a function that generates a tensor filled with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
x = torch.ones(2, 3, dtype=torch.int)
# torch.ones(2, 3, dtype=torch.int) is a function that generates a tensor of shape (2, 3) filled with ones and of type int
print(x.dtype)
# torch.int is an alias for torch.int32, which is a 32-bit integer type
# can be double/float, int, etc.
# torch.float is an alias for torch.float32, which is a 32-bit floating point type or even float16, etc.
# torch.double is an alias for torch.float64, which is a 64-bit floating point type
print(x.size())
# x.size() returns the size of the tensor, which is (2, 3) in this case

torch.int32
torch.Size([2, 3])


In [18]:
x = torch.tensor([[1, 2], [3, 4]])
# torch.tensor([[1, 2], [3, 4]]) creates a tensor from the given list of lists
print(x)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x)
print(y)
z = x + y
z = torch.add(x, y)
# operations are add, sub, mul, div, etc.
# torch.add(x, y) adds the two tensors x and y element-wise
print(z)
# The above code creates two random tensors x and y of shape (2, 2) and adds them together to create a new tensor z

tensor([[ 0.3686,  0.9801],
        [-0.5222,  0.6155]])
tensor([[ 2.1255,  1.8262],
        [-0.3254, -0.0393]])
tensor([[ 2.4940,  2.8063],
        [-0.8475,  0.5762]])


In [ ]:
y.add_(x)
# The underscore at the end of the function name indicates that this operation modifies y in place

# in pytorch all functions that modify the tensor in place have an underscore at the end of the function name

tensor([[ 2.8626,  3.7864],
        [-1.3697,  1.1917]])

In [ ]:
x = torch.randn(2, 3, 4)
# torch.randn(2, 3, 4) creates a tensor of shape (2, 3, 4) with random values from a normal distribution with mean 0 and variance 1