In [2]:
import torch

In [3]:
x = torch.empty((2, 3))
# torch.empty creates an uninitialized tensor of the given size
# The values in the tensor are not set to zero or any other value
print(x)

tensor([[5.7798e-34, 1.4433e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
torch.rand(2, 3)
# torch.rand(2, 3) is a function that generates a tensor of shape (2, 3) with random values between 0 and 1

tensor([[0.5249, 0.4773, 0.8245],
        [0.5138, 0.4193, 0.1511]])

In [5]:
torch.zeros(2, 3)
# torch.zeros(2, 3) is a function that generates a tensor of shape (2, 3) filled with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2, 3)
# torch.ones() is a function that generates a tensor filled with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
x = torch.ones(2, 3, dtype=torch.int)
# torch.ones(2, 3, dtype=torch.int) is a function that generates a tensor of shape (2, 3) filled with ones and of type int
print(x.dtype)
# torch.int is an alias for torch.int32, which is a 32-bit integer type
# can be double/float, int, etc.
# torch.float is an alias for torch.float32, which is a 32-bit floating point type or even float16, etc.
# torch.double is an alias for torch.float64, which is a 64-bit floating point type
print(x.size())
# x.size() returns the size of the tensor, which is (2, 3) in this case

torch.int32
torch.Size([2, 3])


In [8]:
x = torch.tensor([[1, 2], [3, 4]])
# torch.tensor([[1, 2], [3, 4]]) creates a tensor from the given list of lists
print(x)

tensor([[1, 2],
        [3, 4]])


In [9]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x)
print(y)
z = x + y
z = torch.add(x, y)
# operations are add, sub, mul, div, etc.
# torch.add(x, y) adds the two tensors x and y element-wise
print(z)
# The above code creates two random tensors x and y of shape (2, 2) and adds them together to create a new tensor z

tensor([[-2.4501, -0.1427],
        [ 0.2458,  0.3241]])
tensor([[-1.0280, -1.4475],
        [ 1.1182, -1.4058]])
tensor([[-3.4781, -1.5903],
        [ 1.3640, -1.0817]])


In [10]:
y.add_(x)
# The underscore at the end of the function name indicates that this operation modifies y in place

# in pytorch all functions that modify the tensor in place have an underscore at the end of the function name

tensor([[-3.4781, -1.5903],
        [ 1.3640, -1.0817]])

In [11]:
x = torch.randn(2, 3)
# torch.randn(2, 3, 4) creates a tensor of shape (2, 3, 4) with random values from a normal distribution with mean 0 and variance 1
# now tensor slicing
print(x[0])
# x[0] selects the first slice of the tensor x along the first dimension (0th dimension)
print(x[:, 0])
# x[:, 0] selects all rows and the first column of the tensor x
print(x[0, :])
# x[0, :] selects the first row and all columns of the tensor x
print(x[0, 0])
# x[0, 0] selects the first element of the first row of the tensor x
print(x[0, 0].item())
# x[0, 0].item() returns the value of the first element of the first row of the tensor x as a Python number
# The item() method is used to convert a single-element tensor to a Python number


tensor([ 0.3762, -0.9219, -0.8240])
tensor([0.3762, 0.2794])
tensor([ 0.3762, -0.9219, -0.8240])
tensor(0.3762)
0.37617406249046326


In [ ]:
# Reshaping tensors
x = torch.randn(4, 4)
print(x)
print(x.view(16))
y = x.view(16)
# x.view(16) reshapes the tensor x to a 1D tensor of size 16
print(y)
print(y.size())
y = x.view(-1, 8)
# x.view(-1, 8) reshapes the tensor x to a 2D tensor with 8 columns and as many rows as needed to accommodate all elements of x
# The -1 indicates that the number of rows should be inferred from the total number of elements in x
print(y)
print(y.size())
# The view() method is used to reshape a tensor without changing its data

tensor([[-1.8844, -0.5562, -0.1677, -0.9045],
        [-1.0257, -0.3969,  0.1745,  0.5870],
        [ 0.3564,  1.2664, -0.2986, -0.2939],
        [ 1.2785, -0.0758,  1.3330,  0.5810]])
tensor([-1.8844, -0.5562, -0.1677, -0.9045, -1.0257, -0.3969,  0.1745,  0.5870,
         0.3564,  1.2664, -0.2986, -0.2939,  1.2785, -0.0758,  1.3330,  0.5810])
torch.Size([16])
tensor([[-1.8844, -0.5562, -0.1677, -0.9045, -1.0257, -0.3969,  0.1745,  0.5870],
        [ 0.3564,  1.2664, -0.2986, -0.2939,  1.2785, -0.0758,  1.3330,  0.5810]])
torch.Size([2, 8])
