In [3]:
# 1) Design model (input, output size, forward pass)
# 2) Construct loss and optimizer
# 3) Training loop
#    -> forward pass: compute prediction
#    -> backward pass: gradients
#    -> update weights
#    -> update learning rate (optional)
# 4) Test the model (on test set)
# 5) Save the model (optional)
# 6) Load the model (optional)
# 7) Inference (optional)
# 8) Visualize (optional)
# 9) Hyperparameter tuning (optional)
# 10) Deployment (optional)
# 11) Documentation (optional)
# 12) Version control (optional)
# 13) Code review (optional)
# 14) Refactoring (optional)
# 15) Testing (optional)
# 16) Debugging (optional)
# 17) Profiling (optional)
# 18) Optimization (optional)
# 19) Experiment tracking (optional)
# 20) Collaboration (optional)

import torch
import torch.nn as nn


In [4]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8, 10], dtype=torch.float32)

# Random weight initialization
w = torch.rand(1, dtype=torch.float32, requires_grad=True)


def forward(x):
    return w * x


# Training loop
learning_rate = 0.01
n_epochs = 50

# Mean Squared Error (MSE) loss function
loss = nn.MSELoss()
# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.SGD([w], lr=learning_rate)

for epoch in range(n_epochs):
    # Forward pass
    y_pred = forward(x)

    # Compute loss
    l = loss(y, y_pred)

    # Compute gradients using backward pass
    l.backward()  # This computes the gradients of the loss w.r.t.(with respect to) the weights

    # Update weights
    optimizer.step()  # This updates the weights using the computed gradients

    # Zero the gradients after updating weights
    optimizer.zero_grad()  # This clears the gradients for the next iteration

    # Print loss and weight every 2 epochs
    if epoch % 2 == 0:
        print(f"Epoch {epoch}, Weight: {w}, Loss: {l}")

Epoch 0, Weight: tensor([1.2021], requires_grad=True), Loss: 11.51176929473877
Epoch 2, Weight: tensor([1.5145], requires_grad=True), Loss: 4.261088848114014
Epoch 4, Weight: tensor([1.7046], requires_grad=True), Loss: 1.577244758605957
Epoch 6, Weight: tensor([1.8203], requires_grad=True), Loss: 0.5838179588317871
Epoch 8, Weight: tensor([1.8907], requires_grad=True), Loss: 0.21610021591186523
Epoch 10, Weight: tensor([1.9335], requires_grad=True), Loss: 0.07998950779438019
Epoch 12, Weight: tensor([1.9595], requires_grad=True), Loss: 0.029608095064759254
Epoch 14, Weight: tensor([1.9754], requires_grad=True), Loss: 0.010959481820464134
Epoch 16, Weight: tensor([1.9850], requires_grad=True), Loss: 0.004056635778397322
Epoch 18, Weight: tensor([1.9909], requires_grad=True), Loss: 0.0015015773242339492
Epoch 20, Weight: tensor([1.9945], requires_grad=True), Loss: 0.0005558113334700465
Epoch 22, Weight: tensor([1.9966], requires_grad=True), Loss: 0.00020573855726979673
Epoch 24, Weight: 

In [16]:
# creating a model now

x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8, 10], dtype=torch.float32)

print(f"Original x shape: {x.shape}")  # Output: torch.Size([5])
print(f"Original y shape: {y.shape}")  # Output: torch.Size([5])
print("-" * 20)

x_reshaped = x.reshape((5, 1))
y_reshaped = y.reshape((-1, 1))  # Using -1 for the first dimension is common
# when you want to infer the size of that dimension based on the other dimensions.
# In this case, it will automatically calculate the size of the first dimension to be 5,
# since the second dimension is set to 1.
print(f"x_reshaped shape: {x_reshaped.shape}")  # Output: torch.Size([5, 1])
print(f"y_reshaped shape: {y_reshaped.shape}")  # Output: torch.Size([5, 1])
print("x_reshaped data:")
print(x_reshaped)

x = x_reshaped
y = y_reshaped


Original x shape: torch.Size([5])
Original y shape: torch.Size([5])
--------------------
x_reshaped shape: torch.Size([5, 1])
y_reshaped shape: torch.Size([5, 1])
x_reshaped data:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])


In [17]:
n_samples, n_features = x_reshaped.shape
print(f"Number of samples: {n_samples}, Number of features: {n_features}")

input_size = n_features
output_size = n_features
print(f"Input size: {input_size}, Output size: {output_size}")

model = nn.Linear(input_size, output_size)
print(f"Model: {model}")

# x_test = torch.tensor([6, 7, 8], dtype=torch.float32).reshape(-1, 1)
x_test = torch.tensor([6], dtype=torch.float32)
print(f"x_test shape: {x_test.shape}")  # Output: torch.Size([3, 1])

print(f"Prediction: {model(x_test)}")

Number of samples: 5, Number of features: 1
Input size: 1, Output size: 1
Model: Linear(in_features=1, out_features=1, bias=True)
x_test shape: torch.Size([1])
Prediction: tensor([-4.0682], grad_fn=<ViewBackward0>)


In [22]:
# Training loop
learning_rate = 0.01
n_epochs = 50

# Mean Squared Error (MSE) loss function
loss = nn.MSELoss()
# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_epochs):
    # Forward pass
    y_pred = model(x)

    # Compute loss
    l = loss(y, y_pred)

    # Compute gradients using backward pass
    l.backward()  # This computes the gradients of the loss w.r.t.(with respect to) the weights

    # Update weights
    optimizer.step()  # This updates the weights using the computed gradients

    # Zero the gradients after updating weights
    optimizer.zero_grad()  # This clears the gradients for the next iteration

    # Print loss and weight every 2 epochs
    if epoch % 2 == 0:
        # Print the model parameters (weights and bias)
        [w, b] = model.parameters()
        print(f"Epoch {epoch}, Weight: {w[0][0].item()}, Bias: {b}, Loss: {l}")
        # print(f"Epoch {epoch}, Weight: {w}, Loss: {l}")


Epoch 0, Weight: 1.9138875007629395, Bias: Parameter containing:
tensor([0.3109], requires_grad=True), Loss: 0.017712455242872238
Epoch 2, Weight: 1.914468765258789, Bias: Parameter containing:
tensor([0.3088], requires_grad=True), Loss: 0.01747407577931881
Epoch 4, Weight: 1.915046215057373, Bias: Parameter containing:
tensor([0.3067], requires_grad=True), Loss: 0.017238985747098923
Epoch 6, Weight: 1.9156196117401123, Bias: Parameter containing:
tensor([0.3046], requires_grad=True), Loss: 0.01700700633227825
Epoch 8, Weight: 1.916189193725586, Bias: Parameter containing:
tensor([0.3026], requires_grad=True), Loss: 0.01677817292511463
Epoch 10, Weight: 1.916754961013794, Bias: Parameter containing:
tensor([0.3005], requires_grad=True), Loss: 0.01655239425599575
Epoch 12, Weight: 1.9173169136047363, Bias: Parameter containing:
tensor([0.2985], requires_grad=True), Loss: 0.016329707577824593
Epoch 14, Weight: 1.917875051498413, Bias: Parameter containing:
tensor([0.2965], requires_grad=